server:
  port: 9217
spring:
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  datasource:
    url: jdbc:postgresql://dpg-d5j04pfpm1nc73fisbd0-a.virginia-postgres.render.com:5432/ecommerce_pa8o?
    username: ecommerce_pa8o_user
    password: Np9UFBpiFzS8OezcJA6q4wm9qphKJjqk
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    expiration: 86400000  # 1 day in milliseconds